# Generated by Django 6.0.1 on 2026-04-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='assinatura_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='pessoa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='setor_origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
