# Generated by Django 6.0.1 on 2026-02-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervalo",
                    models.CharField(
                        choices=[
                            ("1h", "1 hora antes"),
                            ("24h", "24 horas antes"),
                            ("48h", "48 horas antes"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(help_text="Formato: +55xxxxxxxxxx", max_length=20),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("enviado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Lembrete",
                "verbose_name_plural": "Configurações de Lembretes",
                "ordering": ["-criado_em"],
                "unique_together": {("evento", "intervalo", "telefone")},
            },
        ),
    ]
