# Generated by Django 6.0.1 on 2026-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderconfig",
            name="mensagem",
            field=models.TextField(
                blank=True,
                help_text="Mensagem personalizada. Placeholders: {evento_nome}, {data_evento}, {intervalo}.",
            ),
        ),
        migrations.AddField(
            model_name="reminderconfig",
            name="midia",
            field=models.FileField(
                blank=True,
                help_text="Opcional: imagem/figurinha para enviar junto com a mensagem.",
                null=True,
                upload_to="whatsapp/",
            ),
        ),
        migrations.AddField(
            model_name="reminderconfig",
            name="midia_url",
            field=models.URLField(
                blank=True,
                help_text="Opcional: URL publica de imagem/figurinha para envio via WhatsApp.",
            ),
        ),
    ]
