# Generated by Django 6.0.1 on 2026-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_centrocusto_configuracaosistema_evento_centro_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='nome_sistema',
            field=models.CharField(default='CycloHub', max_length=80),
        ),
    ]
