# Generated by Django 6.0.1 on 2026-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-data_inicio"],
            },
        ),
    ]
