# Generated by Django 6.0.1 on 2026-01-19 18:59

import datetime

import django.db.models.deletion
from django.conf import settings
from django.utils import timezone
from django.db import migrations, models


def convert_evento_datas(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")
    tz = timezone.get_current_timezone()
    for evento in Evento.objects.all().only("id", "data_inicio", "data_fim"):
        if evento.data_inicio:
            data_inicio = evento.data_inicio
            if isinstance(data_inicio, datetime.datetime):
                data_inicio = data_inicio.date()
            inicio_dt = datetime.datetime.combine(data_inicio, datetime.time.min)
            if timezone.is_naive(inicio_dt):
                inicio_dt = timezone.make_aware(inicio_dt, tz)
            evento.data_inicio = inicio_dt
        if evento.data_fim:
            data_fim = evento.data_fim
            if isinstance(data_fim, datetime.datetime):
                data_fim = data_fim.date()
            fim_dt = datetime.datetime.combine(data_fim, datetime.time(23, 59, 59))
            if timezone.is_naive(fim_dt):
                fim_dt = timezone.make_aware(fim_dt, tz)
            evento.data_fim = fim_dt
        evento.save(update_fields=["data_inicio", "data_fim"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="adicional_chale",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="evento",
            name="fechado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="prev_participantes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="prev_trabalhadores",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="responsavel_geral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANEJADO", "Planejado"),
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("ENCERRADO", "Encerrado"),
                ],
                default="PLANEJADO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="taxa_base",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="evento",
            name="taxa_trabalhador",
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_fim",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateTimeField(),
        ),
        migrations.RunPython(convert_evento_datas, migrations.RunPython.noop),
    ]
