# Generated by Codex on 2026-01-20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_evento_adicional_chale_evento_fechado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=2048)),
                ("view_name", models.CharField(blank=True, max_length=255)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de auditoria",
                "verbose_name_plural": "Logs de auditoria",
                "ordering": ["-created_at"],
            },
        ),
    ]
