# Generated by Django 6.0.1 on 2026-02-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Centro de custo",
                "verbose_name_plural": "Centros de custo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_sistema", models.CharField(default="Eventa", max_length=80)),
                (
                    "rotulo_evento_singular",
                    models.CharField(default="Evento", max_length=40),
                ),
                (
                    "rotulo_evento_plural",
                    models.CharField(default="Eventos", max_length=40),
                ),
                ("modulo_financeiro_ativo", models.BooleanField(default=True)),
                ("modulo_estoque_ativo", models.BooleanField(default=True)),
                ("modulo_hospedagem_ativo", models.BooleanField(default=True)),
                ("modulo_notificacoes_ativo", models.BooleanField(default=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracao do sistema",
                "verbose_name_plural": "Configuracoes do sistema",
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="core.centrocusto",
            ),
        ),
    ]
