# Generated by Django 6.0.1 on 2026-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodging", "0003_reservachale_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservachale",
            name="idades_criancas",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="reservachale",
            name="qtd_criancas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
