# Generated by Django 6.0.1 on 2026-02-13 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_centrocusto_configuracaosistema_evento_centro_custo"),
        ("lodging", "0004_reservachale_idades_criancas_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcaoChale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("BLOQUEIO", "Bloqueio"), ("MANUTENCAO", "Manutencao")], max_length=20)),
                ("titulo", models.CharField(max_length=120)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Acao de chale",
                "verbose_name_plural": "Acoes de chale",
                "ordering": ["-data_inicio", "-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="reservachale",
            name="unique_chale_por_evento",
        ),
        migrations.AddField(
            model_name="reservachale",
            name="data_entrada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservachale",
            name="data_saida",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acaochale",
            name="atualizado_por",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="acoes_chale_atualizadas", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="acaochale",
            name="chale",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="acoes_periodo", to="lodging.chale"),
        ),
        migrations.AddField(
            model_name="acaochale",
            name="criado_por",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="acoes_chale_criadas", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="acaochale",
            name="evento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.evento"),
        ),
    ]
