# Generated by Codex on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodging", "0005_acaochale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservachale",
            name="detalhes_necessidade_especial",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reservachale",
            name="possui_necessidade_especial",
            field=models.BooleanField(default=False),
        ),
    ]

