# Generated by Django 6.0.1 on 2026-01-20 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_evento_adicional_chale_evento_fechado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("capacidade", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("MANUTENCAO", "Manutencao"),
                            ("INATIVO", "Inativo"),
                        ],
                        default="ATIVO",
                        max_length=20,
                    ),
                ),
                ("acessivel_cadeirante", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Chale",
                "verbose_name_plural": "Chales",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ReservaChale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responsavel_nome", models.CharField(max_length=120)),
                ("qtd_pessoas", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRE_RESERVA", "Pre-reserva"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PRE_RESERVA",
                        max_length=20,
                    ),
                ),
                (
                    "valor_adicional",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="lodging.chale"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.evento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de chale",
                "verbose_name_plural": "Reservas de chale",
                "ordering": ["-criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "CONFIRMADA")),
                        fields=("evento", "chale"),
                        name="unique_chale_confirmado_por_evento",
                    )
                ],
            },
        ),
    ]
