# Generated by Codex on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservachale",
            name="unique_chale_confirmado_por_evento",
        ),
        migrations.AddConstraint(
            model_name="reservachale",
            constraint=models.UniqueConstraint(
                fields=("evento", "chale"),
                name="unique_chale_por_evento",
            ),
        ),
    ]
