# Generated by Codex on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("lodging", "0002_unique_chale_por_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservachale",
            name="pago",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservachale",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[("DINHEIRO", "Dinheiro"), ("PIX", "PIX"), ("CARTAO", "Cartao"), ("OUTRO", "Outro")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reservachale",
            name="conta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                to="finance.contacaixa",
            ),
        ),
        migrations.AddField(
            model_name="reservachale",
            name="lancamento_financeiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="reservas_chale",
                to="finance.lancamentofinanceiro",
            ),
        ),
    ]
