# Generated by Django 6.0.1 on 2026-04-09 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_alter_configuracaosistema_nome_sistema"),
        ("inventory", "0005_produto_estoque_reabastecimento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendaMobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_referencia",
                    models.CharField(
                        help_text="Timestamp ou ID gerado no frontend",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("forma_pagamento", models.CharField(max_length=20)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas_mobile",
                        to="core.evento",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas_mobile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda Mobile",
                "verbose_name_plural": "Vendas Mobile",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="ItemVendaMobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pos.vendamobile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Venda Mobile",
                "verbose_name_plural": "Itens da Venda Mobile",
            },
        ),
    ]
