# Generated by Django 6.0.1 on 2026-06-21 00:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_configuracaosistema_nome_sistema"),
        ("inventory", "0005_produto_estoque_reabastecimento"),
        ("pos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemvendamobile",
            options={
                "verbose_name": "Item da Venda PDV",
                "verbose_name_plural": "Itens das Vendas PDV",
            },
        ),
        migrations.AlterModelOptions(
            name="vendamobile",
            options={
                "ordering": ["-data_hora"],
                "verbose_name": "Venda PDV",
                "verbose_name_plural": "Vendas PDV",
            },
        ),
        migrations.RemoveField(
            model_name="itemvendamobile",
            name="produto",
        ),
        migrations.AddField(
            model_name="itemvendamobile",
            name="codigo_produto",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="itemvendamobile",
            name="desconto_perc",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Desconto (%)",
            ),
        ),
        migrations.AddField(
            model_name="itemvendamobile",
            name="familia_produto",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="itemvendamobile",
            name="nome_produto",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="vendamobile",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas_pdv",
                to="core.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="vendamobile",
            name="forma_pagamento",
            field=models.CharField(blank=True, default="MISTO", max_length=20),
        ),
        migrations.AlterField(
            model_name="vendamobile",
            name="id_referencia",
            field=models.CharField(
                help_text="Timestamp ou UUID gerado no frontend",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendamobile",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total (R$)"
            ),
        ),
        migrations.AlterField(
            model_name="vendamobile",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas_pdv",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LocalVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome do local"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "modulo_dashboard",
                    models.BooleanField(default=True, verbose_name="Dashboard"),
                ),
                (
                    "modulo_pdv",
                    models.BooleanField(default=True, verbose_name="PDV (Caixa)"),
                ),
                (
                    "modulo_vendas",
                    models.BooleanField(default=True, verbose_name="Vendas"),
                ),
                (
                    "modulo_produtos",
                    models.BooleanField(default=False, verbose_name="Produtos"),
                ),
                (
                    "modulo_estoque",
                    models.BooleanField(default=True, verbose_name="Estoque"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locais_venda",
                        to="core.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de Venda",
                "verbose_name_plural": "Locais de Venda",
                "ordering": ["evento", "nome"],
                "unique_together": {("evento", "nome")},
            },
        ),
        migrations.CreateModel(
            name="FamiliaVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome da família"),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familias",
                        to="pos.localvenda",
                        verbose_name="Local de venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Família de Produtos (PDV)",
                "verbose_name_plural": "Famílias de Produtos (PDV)",
                "ordering": ["local", "nome"],
                "unique_together": {("local", "nome")},
            },
        ),
        migrations.AddField(
            model_name="vendamobile",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="pos.localvenda",
                verbose_name="Local de venda",
            ),
        ),
        migrations.CreateModel(
            name="PagamentoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "PIX"),
                            ("DÉBITO", "Débito"),
                            ("CRÉDITO", "Crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="pos.vendamobile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento da Venda",
                "verbose_name_plural": "Pagamentos das Vendas",
            },
        ),
        migrations.CreateModel(
            name="ProdutoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço de venda (R$)",
                    ),
                ),
                (
                    "estoque_atual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Estoque atual",
                    ),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Estoque mínimo (EM)",
                    ),
                ),
                (
                    "ponto_reabastecimento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ponto de reabastecimento (PR)",
                    ),
                ),
                (
                    "estoque_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Estoque máximo (EMáx)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Ativo no local"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "familia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="pos.familiavenda",
                        verbose_name="Família",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="pos.localvenda",
                        verbose_name="Local de venda",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locais",
                        to="inventory.produto",
                        verbose_name="Produto (catálogo)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto no Local (Sub-estoque)",
                "verbose_name_plural": "Produtos nos Locais (Sub-estoque)",
                "ordering": ["local", "familia", "produto"],
                "unique_together": {("produto", "local")},
            },
        ),
        migrations.CreateModel(
            name="EntradaEstoqueLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Quantidade entrada",
                    ),
                ),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço de custo (R$)",
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço de venda (R$)",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da entrada")),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observação"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entradas_estoque_local",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produto_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="pos.produtolocal",
                        verbose_name="Produto no local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Estoque (Local PDV)",
                "verbose_name_plural": "Entradas de Estoque (Local PDV)",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="itemvendamobile",
            name="produto_local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_venda",
                to="pos.produtolocal",
                verbose_name="Produto no local",
            ),
        ),
    ]
