# Generated by Django 6.0.1 on 2026-02-10 14:44

from datetime import timedelta

from django.db import migrations, models


def preencher_data_hora_envio(apps, schema_editor):
    ReminderConfig = apps.get_model("notifications", "ReminderConfig")

    intervalos_minutos = {
        "1h": 60,
        "24h": 1440,
        "48h": 2880,
    }

    for lembrete in ReminderConfig.objects.select_related("evento").all():
        if lembrete.data_hora_envio:
            continue
        evento = getattr(lembrete, "evento", None)
        data_inicio = getattr(evento, "data_inicio", None)
        if not data_inicio:
            continue
        minutos = intervalos_minutos.get(lembrete.intervalo or "24h", 1440)
        lembrete.data_hora_envio = data_inicio - timedelta(minutes=minutos)
        lembrete.save(update_fields=["data_hora_envio"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_centrocusto_configuracaosistema_evento_centro_custo"),
        ("notifications", "0002_reminderconfig_mensagem_reminderconfig_midia_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reminderconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reminderconfig",
            name="data_hora_envio",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora exatas para envio do lembrete.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reminderconfig",
            name="intervalo",
            field=models.CharField(blank=True, default="24h", max_length=10),
        ),
        migrations.RunPython(preencher_data_hora_envio, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="reminderconfig",
            unique_together={("evento", "data_hora_envio", "telefone")},
        ),
    ]
